/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fase2;

import java.awt.FileDialog;
import java.awt.Frame;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Darkestt
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulos = new javax.swing.JLabel();
        UbicacionArchivo = new javax.swing.JLabel();
        BotonSubirArchivo = new javax.swing.JButton();
        ClassNoticiaTitulo = new javax.swing.JLabel();
        Clasificacion = new javax.swing.JLabel();
        BotonClasificar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        Titulos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Titulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulos.setText("Clasificador de Páginas Web de Noticias");
        getContentPane().add(Titulos);
        Titulos.setBounds(0, 10, 300, 17);

        UbicacionArchivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UbicacionArchivo.setText("Ubicación del Archivo");
        getContentPane().add(UbicacionArchivo);
        UbicacionArchivo.setBounds(10, 70, 280, 20);

        BotonSubirArchivo.setText("Subir Archivo");
        BotonSubirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSubirArchivoMouseClicked(evt);
            }
        });
        BotonSubirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSubirArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSubirArchivo);
        BotonSubirArchivo.setBounds(10, 40, 110, 23);

        ClassNoticiaTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClassNoticiaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ClassNoticiaTitulo.setText("Clasificación de la Noticia");
        getContentPane().add(ClassNoticiaTitulo);
        ClassNoticiaTitulo.setBounds(10, 140, 280, 15);

        Clasificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Clasificacion.setText("Clasificación");
        getContentPane().add(Clasificacion);
        Clasificacion.setBounds(10, 160, 280, 20);

        BotonClasificar.setText("Clasificar");
        BotonClasificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonClasificarMouseClicked(evt);
            }
        });
        BotonClasificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClasificarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonClasificar);
        BotonClasificar.setBounds(10, 100, 110, 23);

        BotonSalir.setText("Salir");
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
        });
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir);
        BotonSalir.setBounds(210, 170, 60, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSubirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSubirArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSubirArchivoActionPerformed

    private void BotonSubirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSubirArchivoMouseClicked
        // TODO add your handling code here:
        String Entrada;
        
        //invocado el frame donde se pide el archivo
        final Frame ventana = new Frame();
        ventana.setSize(400, 220);
        FileDialog fd = new FileDialog(ventana,"Seleccione un archivo",FileDialog.LOAD);
        fd.show();
        File EntradaF = new File(fd.getDirectory(),fd.getFile());
        Entrada = EntradaF.toString();
        
        //mostarndo la ubicacion del archivo al usuario
        UbicacionArchivo.setText(Entrada);
        
        //JOptionPane.showMessageDialog(null,"Archivo: "+UbicacionArchivo.getText());
    }//GEN-LAST:event_BotonSubirArchivoMouseClicked

    private void BotonClasificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClasificarMouseClicked
        // TODO add your handling code here:
        //llamando la clase Clasificador
        String ClaseFinal;
        try {
            Clasificador SeccionNoticia = new Clasificador();  
            if(UbicacionArchivo.getText().equals("Ubicación del Archivo")){
                //JOptionPane.showMessageDialog(null,"Debe seleccionar un archivo.");
                JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo.", 
                    "Error:", JOptionPane.ERROR_MESSAGE);
            }else{
                Clasificacion.setText("Clasificando...");
                ClaseFinal = SeccionNoticia.Clasificar(UbicacionArchivo.getText());
                //Imprimiendo la clase final en la interfaz
                Clasificacion.setText(ClaseFinal);
            }                
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BotonClasificarMouseClicked

    private void BotonClasificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClasificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonClasificarActionPerformed

    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonSalirMouseClicked

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonClasificar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonSubirArchivo;
    private javax.swing.JLabel Clasificacion;
    private javax.swing.JLabel ClassNoticiaTitulo;
    private javax.swing.JLabel Titulos;
    private javax.swing.JLabel UbicacionArchivo;
    // End of variables declaration//GEN-END:variables
}
